    image: node:latest

    stages:
      - build
      - test
      - deploy

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

    testing_testing:
      stage: test
      script: npm test
    
    deploy_project:
      stage: deploy
      script: npm run build