const REDUCER = 'list-card';
const SEARCH_CARDS = `${REDUCER}:SEARCH_CARDS`;
const API_SEARCH_CARDS = `${REDUCER}:API_SEARCH_CARDS`;
const RESET_CARDS = `${REDUCER}:RESET_CARDS`;

export { REDUCER, SEARCH_CARDS, API_SEARCH_CARDS, RESET_CARDS };
