const REDUCER = 'card';
const SEARCH_CARD = `${REDUCER}:SEARCH_CARD`;
const SEARCH_COMPLEMENTS_CARD = `${REDUCER}:SEARCH_COMPLEMENTS_CARD`;
const API_SEARCH_CARD = `${REDUCER}:API_SEARCH_CARD`;
const API_SEARCH_COMICS = `${REDUCER}:API_SEARCH_COMICS`;
const API_SEARCH_EVENTS = `${REDUCER}:API_SEARCH_EVENTS`;
const API_SEARCH_SERIES = `${REDUCER}:API_SEARCH_SERIES`;
const RESET_DESCRIPTION = `${REDUCER}:RESET_DESCRIPTION`;
const RESET_COMICS = `${REDUCER}:RESET_COMICS`;
const RESET_EVENTS = `${REDUCER}:RESET_EVENTS`;
const RESET_SERIES = `${REDUCER}:RESET_SERIES`;
const RESET_CARD = `${REDUCER}:RESET_CARD`;

export {
  REDUCER,
  SEARCH_CARD,
  SEARCH_COMPLEMENTS_CARD,
  API_SEARCH_CARD,
  API_SEARCH_COMICS,
  API_SEARCH_EVENTS,
  API_SEARCH_SERIES,
  RESET_DESCRIPTION,
  RESET_COMICS,
  RESET_EVENTS,
  RESET_SERIES,
  RESET_CARD
};
