const REDUCER = 'card';
const SEARCH_CARD = `${REDUCER}:SEARCH_CARD`;
const SEARCH_COMPLEMENTS_CARD = `${REDUCER}:SEARCH_COMPLEMENTS_CARD`;
const API_SEARCH_CARD = `${REDUCER}:API_SEARCH_CARD`;
const API_SEARCH_COMICS = `${REDUCER}:API_SEARCH_COMICS`;
const API_SEARCH_EVENTS = `${REDUCER}:API_SEARCH_EVENTS`;
const API_SEARCH_SERIES = `${REDUCER}:API_SEARCH_SERIES`;
const API_SEARCH_STORIES = `${REDUCER}:API_SEARCH_STORIES`;

export {
  REDUCER,
  SEARCH_CARD,
  SEARCH_COMPLEMENTS_CARD,
  API_SEARCH_CARD,
  API_SEARCH_COMICS,
  API_SEARCH_EVENTS,
  API_SEARCH_SERIES,
  API_SEARCH_STORIES
};
